language: python
sudo: required
services:
  - docker
cache: pip
os:
  - linux
python:
  - "3.6"
jobs:
  include:
    - stage: test
      script: pip install pipenv
    - stage: test
      script: pipenv install --dev
    - stage: test
      script: pipenv install ./
    - stage: test
      script: pipenv run nose2 -s arxiv --with-coverage && coveralls
    - stage: test 
      script: ./tests/lintstats.sh
    - stage: deploy
      if: tag IS present
      script: pip install twine && python setup.py sdist && twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
